version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Install Dependencies
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends git curl ca-certificates
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="20.10.10"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run: ./test.sh
