name: Docker

on:
  push:
    branches:
      - master
  # Run tests for each PRs.
  pull_request: {}

env:
  GHCR_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/review
  HUB_IMAGE_ID: ${{ github.repository_owner }}/review
  REGISTRY_USER_ID: vvakame

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run test
        run: ./test.sh

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        version:
          # bullseye 以降のイメージだけサポート
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "5.7"
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_CR_PAT }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER_ID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "review-${{ matrix.version }}"
          tags: "${{ env.GHCR_IMAGE_ID }}:${{ matrix.version }},${{ env.HUB_IMAGE_ID }}:${{ matrix.version }}"
          platforms: linux/amd64,linux/arm64

  # 最後にpushされたものにlatestが更新されるので他のタグ付きと分ける ついでにビルドもし直していいでしょ…
  push_latest:
    needs: push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_CR_PAT }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER_ID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.GHCR_IMAGE_ID }}:latest,${{ env.HUB_IMAGE_ID }}:latest"
          platforms: linux/amd64,linux/arm64
